# Generated by Django 4.2.7 on 2025-07-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmgmt', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
